apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-nodeapp-traffic
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: nodeapp
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: nodeapp 
    ports:
    - protocol: TCP
      port: 3000
